#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------
    restore0Dir
    runApplication blockMesh
    runApplication surfaceFeatureExtract 

    runApplication snappyHexMesh -overwrite
    runApplication renumberMesh -overwrite
    runApplication checkMesh

    runApplication decomposePar

    runParallel rhoSimpleFoam
    mv log.rhoSimpleFoam log.rhoSimpleFoamRun

    runParallel rhoSimpleFoam -postProcess -func yPlus
    mv log.rhoSimpleFoam log.rhoSimpleFoamYplus

    runParallel rhoSimpleFoam -postProcess -func wallShearStress
    mv log.rhoSimpleFoam log.rhoSimpleFoamWallShearStress

    runParallel rhoSimpleFoam -postProcess -func vorticity
    mv log.rhoSimpleFoam log.rhoSimpleFoamVorticity

    runParallel postProcess -func samplePwall
    mv log.postProcess log.postProcessSamplePwall

    runApplication reconstructPar -latestTime
    touch case.foam